### ISSUE TITLE
Login to Hypothesis not intuitive

### ISSUE THREAD

**Issue by adam3smith** [adam3smith/AnnoREP-Frontend#21]
## System and Software

- Operating System:
- Web Browser: Firefox

## Page or Route

- Link:

## Description

When first showing the annotated article, annotations may not show if user isn't logged into Hypothesis

## Notes

_Any other comments you think may be important to reproducing the issue_

**Comment by tohuynh** [comment]
![image](https://user-images.githubusercontent.com/37560480/137422550-5ebdd309-8a87-4256-a803-3c5c3642fde4.png)
@adam3smith @nniiicc @dkgeorgetown Would this inline notification message in combination with the Annotation sidebar (Hypothesis client) initially being expanded/shown be enough to inform users that in order to see their annotations they would need to log in to Hypothesis using the Annotation sidebar? The place of this inline notification message is immediately above the grey toolbar (which contains the "Show data sources" icon and "Delete manuscript" icon".

**Comment by nniiicc** [comment]
Yes - this is a good solution and we can use in UX tests
